package plugin.types;

public enum EVENT_TYPE {
    BLOCK_BREAK,
    BLOCK_PLACE,
    BLOCK_DAMAGE,
    BLOCK_USE,
    BLOCK_OPEN,
    DOOR_USE,
    FLUID_PLACE,
    FLUID_PICKUP,
    BLOCK_HARVEST,
    BLOCK_GATHER,
    BLOCK_CYCLE,
    CHANGE_BLOCK,
    BUILDER_TOOL,
    ALL
}
